name: new_project
description: A new Flutter project.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  url_launcher: ^6.2.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  test: ^1.25.6

flutter:
  uses-material-design: true